"""Seed Phase 4 — Populate Skills Hub with real skills from major registries."""
import asyncio
import aiosqlite
import json
import uuid

DB_PATH = "/data/users/LJTvWmv8w3YZfYb6dMwkwprDPJv1/Workspace/openclaw_mission_control/backend/mission_control.db"

SKILLS = [
    # ── skills.sh (Vercel) ──────────────────────────────────────────────
    {
        "name": "agent-browser",
        "description": "Browser automation and web interaction — navigate, click, extract, screenshot via headless browser",
        "category": "development",
        "skill_type": "external",
        "source_url": "https://skills.sh/vercel-labs/agent-browser",
        "version": "2.1.0",
        "prompt_template": "Use browser automation to: {{task}}. Navigate to URLs, interact with elements, extract content, and capture screenshots.",
        "tags": ["browser", "automation", "scraping", "web"],
        "trust_score": 78.0,
    },
    {
        "name": "web-design-guidelines",
        "description": "Web design best practices, accessibility, responsive patterns, and modern CSS guidelines",
        "category": "design",
        "skill_type": "external",
        "source_url": "https://skills.sh/vercel-labs/agent-skills",
        "version": "1.4.0",
        "prompt_template": "Apply web design best practices to: {{task}}. Consider accessibility (WCAG 2.1), responsive design, performance, and modern CSS patterns.",
        "tags": ["design", "accessibility", "css", "responsive"],
        "trust_score": 85.0,
    },
    {
        "name": "vercel-composition-patterns",
        "description": "Vercel deployment composition patterns — monorepo configs, edge functions, ISR, and middleware",
        "category": "development",
        "skill_type": "external",
        "source_url": "https://skills.sh/vercel-labs/agent-skills",
        "version": "1.2.0",
        "prompt_template": "Implement Vercel deployment patterns for: {{task}}. Use appropriate composition patterns including monorepo, edge functions, ISR, and middleware.",
        "tags": ["vercel", "deployment", "edge", "serverless"],
        "trust_score": 72.0,
    },
    {
        "name": "soultrace",
        "description": "AI soul tracing and personality analysis — deep behavioral profiling and persona generation",
        "category": "research",
        "skill_type": "external",
        "source_url": "https://skills.sh/soultrace-ai/soultrace-skill",
        "version": "3.0.1",
        "prompt_template": "Perform soul tracing analysis on: {{subject}}. Generate behavioral profile, personality traits, communication patterns, and decision-making tendencies.",
        "tags": ["personality", "analysis", "profiling", "behavioral"],
        "trust_score": 65.0,
    },
    {
        "name": "remotion-best-practices",
        "description": "Remotion video creation framework guidance — programmatic video, motion graphics, and rendering",
        "category": "creative",
        "skill_type": "external",
        "source_url": "https://skills.sh/remotion-dev/skills",
        "version": "1.1.0",
        "prompt_template": "Create Remotion video components for: {{task}}. Follow best practices for composition, animation, and rendering pipeline.",
        "tags": ["video", "remotion", "motion-graphics", "rendering"],
        "trust_score": 70.0,
    },

    # ── Microsoft Azure Skills (via skills.sh) ─────────────────────────
    {
        "name": "azure-cost-optimization",
        "description": "Azure cost analysis and optimization — identify savings, right-size resources, reserved instances",
        "category": "cloud",
        "skill_type": "external",
        "source_url": "https://skills.sh/microsoft/azure-skills",
        "version": "2.3.0",
        "prompt_template": "Analyze Azure costs for: {{subscription_or_resource_group}}. Identify optimization opportunities including right-sizing, reserved instances, and unused resources.",
        "tags": ["azure", "cost", "optimization", "cloud", "finops"],
        "trust_score": 90.0,
    },
    {
        "name": "azure-kubernetes",
        "description": "Kubernetes on Azure (AKS) management — cluster ops, scaling, networking, and monitoring",
        "category": "cloud",
        "skill_type": "external",
        "source_url": "https://skills.sh/microsoft/azure-skills",
        "version": "2.1.0",
        "prompt_template": "Manage Azure Kubernetes Service for: {{task}}. Handle cluster operations, scaling, networking policies, and monitoring setup.",
        "tags": ["azure", "kubernetes", "aks", "devops"],
        "trust_score": 88.0,
    },
    {
        "name": "azure-enterprise-infra-planner",
        "description": "Enterprise infrastructure planning on Azure — landing zones, governance, and multi-subscription design",
        "category": "cloud",
        "skill_type": "external",
        "source_url": "https://skills.sh/microsoft/azure-skills",
        "version": "1.8.0",
        "prompt_template": "Plan Azure enterprise infrastructure for: {{requirements}}. Design landing zones, governance policies, and multi-subscription architecture following Microsoft CAF.",
        "tags": ["azure", "enterprise", "infrastructure", "governance", "caf"],
        "trust_score": 92.0,
    },
    {
        "name": "azure-ai",
        "description": "Azure AI services integration — OpenAI Service, Cognitive Services, and AI search",
        "category": "cloud",
        "skill_type": "external",
        "source_url": "https://skills.sh/microsoft/github-copilot-for-azure",
        "version": "1.5.0",
        "prompt_template": "Integrate Azure AI services for: {{task}}. Configure OpenAI endpoints, cognitive services, or AI search as needed.",
        "tags": ["azure", "ai", "openai", "cognitive-services"],
        "trust_score": 85.0,
    },
    {
        "name": "azure-messaging",
        "description": "Azure messaging services — Service Bus, Event Hubs, Event Grid, and queue management",
        "category": "cloud",
        "skill_type": "external",
        "source_url": "https://skills.sh/microsoft/github-copilot-for-azure",
        "version": "1.3.0",
        "prompt_template": "Configure Azure messaging services for: {{task}}. Set up Service Bus, Event Hubs, or Event Grid with appropriate routing and dead-letter handling.",
        "tags": ["azure", "messaging", "service-bus", "event-hubs"],
        "trust_score": 82.0,
    },

    # ── Skills Directory (skillsdirectory.com) ──────────────────────────
    {
        "name": "venture-assessment",
        "description": "VC investment assessment reports — market analysis, team evaluation, and deal scoring",
        "category": "business",
        "skill_type": "external",
        "source_url": "https://www.skillsdirectory.com/skills/venture-assessment",
        "version": "1.0.0",
        "prompt_template": "Perform venture assessment on: {{company_or_pitch}}. Evaluate market size, team strength, product-market fit, competitive landscape, and provide investment recommendation.",
        "tags": ["vc", "investment", "assessment", "business"],
        "trust_score": 75.0,
    },
    {
        "name": "thinking-session",
        "description": "Structured deep thinking with Socratic dialogue — explore problems through guided questioning",
        "category": "research",
        "skill_type": "external",
        "source_url": "https://www.skillsdirectory.com/skills/thinking-session",
        "version": "1.0.0",
        "prompt_template": "Conduct a thinking session on: {{topic}}. Use Socratic dialogue to explore assumptions, identify blind spots, and reach deeper understanding through structured questioning.",
        "tags": ["thinking", "socratic", "reasoning", "exploration"],
        "trust_score": 80.0,
    },
    {
        "name": "icp-generator",
        "description": "Ideal Customer Profile generation — define target audience with firmographics, pain points, and buying signals",
        "category": "business",
        "skill_type": "external",
        "source_url": "https://www.skillsdirectory.com/skills/icp-generator",
        "version": "1.0.0",
        "prompt_template": "Generate an Ideal Customer Profile for: {{product_or_service}}. Define firmographics, pain points, buying signals, and decision-maker personas.",
        "tags": ["marketing", "icp", "customer-profile", "gtm"],
        "trust_score": 72.0,
    },
    {
        "name": "context-engineering",
        "description": "Advanced context engineering for AI agents — prompt optimization, context window management, and retrieval strategies",
        "category": "development",
        "skill_type": "external",
        "source_url": "https://www.skillsdirectory.com/skills/context-engineering",
        "version": "2.0.0",
        "prompt_template": "Apply context engineering to: {{task}}. Optimize prompt structure, manage context windows, implement RAG strategies, and ensure efficient token usage.",
        "tags": ["context", "prompting", "rag", "optimization"],
        "trust_score": 88.0,
    },
    {
        "name": "legal-contract-review",
        "description": "AI-assisted legal contract review — identify risks, unusual clauses, and compliance issues",
        "category": "legal",
        "skill_type": "external",
        "source_url": "https://www.skillsdirectory.com/skills/legal-contract-review",
        "version": "1.1.0",
        "prompt_template": "Review this legal contract: {{contract_text}}. Identify unusual clauses, potential risks, compliance issues, and missing protections. Provide clause-by-clause analysis.",
        "tags": ["legal", "contract", "review", "compliance"],
        "trust_score": 70.0,
    },

    # ── Anthropic Skills (github.com/anthropics/skills) ─────────────────
    {
        "name": "pdf-documents",
        "description": "PDF document creation, editing, form extraction, and text manipulation via Python",
        "category": "document",
        "skill_type": "external",
        "source_url": "https://github.com/anthropics/skills/tree/main/skills/pdf",
        "version": "1.2.0",
        "prompt_template": "Work with PDF documents: {{task}}. Create, edit, extract text/forms, merge, or split PDFs using Python libraries (PyPDF2, reportlab, pdfplumber).",
        "tags": ["pdf", "document", "extraction", "report"],
        "trust_score": 95.0,
    },
    {
        "name": "docx-documents",
        "description": "Word document creation and editing — formatting, tables, headers, and mail merge",
        "category": "document",
        "skill_type": "external",
        "source_url": "https://github.com/anthropics/skills/tree/main/skills/docx",
        "version": "1.1.0",
        "prompt_template": "Create or edit Word documents: {{task}}. Use python-docx to generate formatted documents with headers, tables, styles, and mail merge.",
        "tags": ["docx", "word", "document", "formatting"],
        "trust_score": 94.0,
    },
    {
        "name": "pptx-presentations",
        "description": "PowerPoint presentation creation and editing — slides, charts, layouts, and templates",
        "category": "document",
        "skill_type": "external",
        "source_url": "https://github.com/anthropics/skills/tree/main/skills/pptx",
        "version": "1.0.0",
        "prompt_template": "Create PowerPoint presentations: {{task}}. Use python-pptx to generate slides with titles, content, charts, images, and custom layouts.",
        "tags": ["pptx", "powerpoint", "presentation", "slides"],
        "trust_score": 92.0,
    },
    {
        "name": "xlsx-spreadsheets",
        "description": "Excel spreadsheet creation and editing — formulas, charts, pivot tables, and data analysis",
        "category": "document",
        "skill_type": "external",
        "source_url": "https://github.com/anthropics/skills/tree/main/skills/xlsx",
        "version": "1.0.0",
        "prompt_template": "Create or edit Excel spreadsheets: {{task}}. Use openpyxl to generate workbooks with formulas, charts, formatting, and data validation.",
        "tags": ["xlsx", "excel", "spreadsheet", "data"],
        "trust_score": 93.0,
    },
    {
        "name": "claude-api-integration",
        "description": "Claude API integration and usage — conversations, tool use, streaming, and batch processing",
        "category": "development",
        "skill_type": "external",
        "source_url": "https://github.com/anthropics/skills/tree/main/skills/claude-api",
        "version": "1.3.0",
        "prompt_template": "Integrate Claude API for: {{task}}. Implement conversations, tool use, streaming, batch processing, or prompt caching as needed.",
        "tags": ["claude", "api", "anthropic", "integration"],
        "trust_score": 98.0,
    },
    {
        "name": "skill-creator",
        "description": "Create and package custom Claude skills — generate SKILL.md, validate structure, and publish",
        "category": "development",
        "skill_type": "external",
        "source_url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
        "version": "1.5.0",
        "prompt_template": "Create a new skill for: {{purpose}}. Generate SKILL.md with instructions, validate the structure, and prepare for publishing to a registry.",
        "tags": ["skill", "creator", "packaging", "meta"],
        "trust_score": 96.0,
    },

    # ── Hugging Face Skills (github.com/huggingface/skills) ─────────────
    {
        "name": "hf-dataset-creator",
        "description": "Create and manage Hugging Face datasets — upload, version, and document datasets on the Hub",
        "category": "data",
        "skill_type": "external",
        "source_url": "https://github.com/huggingface/skills/tree/main/skills/hf-dataset-creator",
        "version": "1.0.0",
        "prompt_template": "Create a Hugging Face dataset for: {{data_description}}. Generate dataset card, create loading script, upload to Hub, and document features.",
        "tags": ["huggingface", "dataset", "ml", "data"],
        "trust_score": 90.0,
    },
    {
        "name": "hf-model-evaluation",
        "description": "Evaluate models and manage evaluation results on Hugging Face — benchmarks, metrics, and leaderboards",
        "category": "data",
        "skill_type": "external",
        "source_url": "https://github.com/huggingface/skills/tree/main/skills/hf-model-evaluation",
        "version": "1.0.0",
        "prompt_template": "Evaluate model performance for: {{model_name}}. Run benchmarks, compute metrics, and submit results to Hugging Face leaderboards.",
        "tags": ["huggingface", "evaluation", "benchmarks", "metrics"],
        "trust_score": 88.0,
    },
    {
        "name": "hf-llm-trainer",
        "description": "Train and fine-tune LLMs on Hugging Face Jobs — SFT, RLHF, and LoRA configurations",
        "category": "data",
        "skill_type": "external",
        "source_url": "https://github.com/huggingface/skills/tree/main/skills/hf-llm-trainer",
        "version": "1.1.0",
        "prompt_template": "Train or fine-tune an LLM for: {{task}}. Configure training job on HF Jobs with appropriate hyperparameters, dataset, and method (SFT, RLHF, LoRA).",
        "tags": ["huggingface", "training", "llm", "fine-tuning"],
        "trust_score": 85.0,
    },
    {
        "name": "hf-papers-research",
        "description": "Research paper lookup and analysis on Hugging Face — find papers, summarize, and compare approaches",
        "category": "research",
        "skill_type": "external",
        "source_url": "https://github.com/huggingface/skills/tree/main/skills/huggingface-papers",
        "version": "1.0.0",
        "prompt_template": "Research papers on: {{topic}}. Search Hugging Face Papers, summarize key findings, compare approaches, and identify state-of-the-art methods.",
        "tags": ["huggingface", "papers", "research", "arxiv"],
        "trust_score": 82.0,
    },
    {
        "name": "hf-best-models",
        "description": "Find best models via Hugging Face leaderboards — Open LLM Leaderboard, text generation, and domain-specific rankings",
        "category": "data",
        "skill_type": "external",
        "source_url": "https://github.com/huggingface/skills/tree/main/skills/huggingface-best-model",
        "version": "1.0.0",
        "prompt_template": "Find the best model for: {{task}}. Search Hugging Face leaderboards, compare models by benchmark scores, size, and licensing.",
        "tags": ["huggingface", "models", "leaderboard", "selection"],
        "trust_score": 87.0,
    },

    # ── Internal Skills (OpenClaw native) ───────────────────────────────
    {
        "name": "Code Review",
        "description": "Automated code review — bugs, security issues, best practices, and performance analysis",
        "category": "coding",
        "skill_type": "internal",
        "source_url": "",
        "version": "1.0.0",
        "prompt_template": "Review the following code for bugs, security issues, and best practices: {{code}}",
        "tags": ["review", "security", "quality"],
        "trust_score": 50.0,
    },
    {
        "name": "Bug Hunter",
        "description": "Find and diagnose bugs in code — trace execution paths, identify edge cases, and suggest fixes",
        "category": "coding",
        "skill_type": "internal",
        "source_url": "",
        "version": "1.0.0",
        "prompt_template": "Analyze this code for bugs: {{code}}. Report each bug with severity, location, and fix suggestion.",
        "tags": ["debugging", "quality"],
        "trust_score": 50.0,
    },
    {
        "name": "API Designer",
        "description": "Design RESTful API endpoints and schemas — OpenAPI specs, request/response schemas, error codes",
        "category": "coding",
        "skill_type": "internal",
        "source_url": "",
        "version": "1.0.0",
        "prompt_template": "Design a REST API for: {{requirements}}. Include endpoints, request/response schemas, and error codes.",
        "tags": ["api", "design", "architecture"],
        "trust_score": 50.0,
    },
    {
        "name": "Security Scanner",
        "description": "Scan code for security vulnerabilities — OWASP Top 10, injection, auth issues, and data exposure",
        "category": "security",
        "skill_type": "internal",
        "source_url": "",
        "version": "1.0.0",
        "prompt_template": "Perform a security audit on: {{code}}. Check for OWASP Top 10, injection, auth issues, and data exposure.",
        "tags": ["security", "audit", "owasp"],
        "trust_score": 50.0,
    },
    {
        "name": "Data Analyst",
        "description": "Analyze datasets and generate insights — statistical summaries, trends, outliers, and visualizations",
        "category": "analysis",
        "skill_type": "internal",
        "source_url": "",
        "version": "1.0.0",
        "prompt_template": "Analyze this dataset: {{data}}. Provide statistical summary, trends, outliers, and visualizations.",
        "tags": ["data", "analytics", "statistics"],
        "trust_score": 50.0,
    },
    {
        "name": "ui-ux-pro-max",
        "description": "Advanced UI/UX design patterns — design systems, accessibility, interaction patterns, and responsive layouts",
        "category": "design",
        "skill_type": "external",
        "source_url": "https://skills.sh/nextlevelbuilder/ui-ux-pro-max-skill",
        "version": "1.0.0",
        "prompt_template": "Apply advanced UI/UX design patterns to: {{task}}. Consider design systems, accessibility, micro-interactions, and responsive layouts.",
        "tags": ["ui", "ux", "design", "accessibility"],
        "trust_score": 76.0,
    },
]


async def seed():
    db = await aiosqlite.connect(DB_PATH)
    db.row_factory = aiosqlite.Row

    # Clear existing skills and bindings
    await db.execute("DELETE FROM agent_skill_bindings")
    await db.execute("DELETE FROM skill_registry")

    for skill in SKILLS:
        skill_id = f"skill-{uuid.uuid4().hex[:8]}"
        await db.execute(
            """INSERT INTO skill_registry
            (id, name, description, category, skill_type, source_url, version, prompt_template, input_schema, output_schema, tags, trust_score)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (skill_id, skill["name"], skill["description"], skill["category"],
             skill["skill_type"], skill["source_url"], skill["version"],
             skill["prompt_template"], "{}", "{}",
             json.dumps(skill["tags"]), skill["trust_score"]),
        )

    await db.commit()
    count = (await db.execute_fetchall("SELECT COUNT(*) as cnt FROM skill_registry"))[0]
    print(f"Seeded {dict(count)['cnt']} skills")
    await db.close()


if __name__ == "__main__":
    asyncio.run(seed())
